export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';


export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const CLEAR_SIGNUP_ERROR_FIELD = "CLEAR_SIGNUP_ERROR_FIELD";

export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';

export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';

export const LOGOUT = 'LOGOUT';



export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_LOGIN_CLEAR_ERROR = 'ADMIN_LOGIN_CLEAR_ERROR';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const FETCH_ADMIN_USER_LIST_REQUEST = 'FETCH_ADMIN_USER_LIST_REQUEST';
export const FETCH_ADMIN_USER_LIST_SUCCESS = 'FETCH_ADMIN_USER_LIST_SUCCESS';
export const FETCH_ADMIN_USER_LIST_FAILURE = 'FETCH_ADMIN_USER_LIST_FAILURE';









