# Generated by Django 4.2.4 on 2023-11-05 12:46

from django.conf import settings
from django.db import migrations, models
import server.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="icon",
            field=models.FileField(
                blank=True, null=True, upload_to=server.models.server_icon_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="member",
            field=models.ManyToManyField(
                related_name="servers",
                through="server.ServerMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
