# Generated by Django 4.2.4 on 2023-11-06 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_server_icon_alter_server_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="servermember",
            name="join_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
