# Generated by Django 4.2.4 on 2023-11-24 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0005_invitation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invitation",
        ),
    ]
