# Generated by Django 4.2.4 on 2023-11-16 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webchat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message",
                to="webchat.conversation",
            ),
        ),
    ]
