# Generated by Django 4.2.4 on 2023-10-23 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=50)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("position", models.PositiveIntegerField()),
                ("mentionable", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server_name", models.CharField(max_length=100)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "server_icon",
                    models.ImageField(blank=True, null=True, upload_to="useravatar"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServerMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("join_date", models.DateTimeField(auto_now_add=True)),
                ("assigned_roles", models.ManyToManyField(to="servers_api.role")),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servers_api.server",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servers_api.role",
                    ),
                ),
                (
                    "server_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servers_api.servermember",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="role",
            name="server_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="servers_api.server"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="users",
            field=models.ManyToManyField(
                related_name="roles", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_name", models.CharField(max_length=50)),
                ("channel_type", models.CharField(max_length=10)),
                ("position", models.PositiveIntegerField()),
                ("topic", models.CharField(max_length=100)),
                ("last_message_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_server",
                        to="servers_api.server",
                    ),
                ),
            ],
        ),
    ]
