# Generated by Django 4.2.4 on 2023-10-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servers_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="server_icon",
            field=models.ImageField(blank=True, null=True, upload_to="server-icons"),
        ),
    ]
