# Generated by Django 4.2.4 on 2023-10-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servers_api", "0002_alter_server_server_icon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="role",
            old_name="server_id",
            new_name="server",
        ),
        migrations.AlterField(
            model_name="servermember",
            name="assigned_roles",
            field=models.ManyToManyField(
                related_name="server_members", to="servers_api.role"
            ),
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
    ]
