# Generated by Django 4.2.4 on 2023-10-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_system', '0003_alter_friendrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
    ]
